_DO_NOT_FOLD=${_DO_NOT_FOLD:-}

ABICHECK_URL=${ABICHECK_URL:-}
ABICHECK_VERSION=${ABICHECK_VERSION:-}

APTKEY_STORE_SKS=${APTKEY_STORE_SKS:-}

ADDITIONAL_DEBS=${ADDITIONAL_DEBS:-}

BUILDER=${BUILDER:-}
CATKIN_LINT=${CATKIN_LINT:-}
CATKIN_LINT_ARGS=${CATKIN_LINT_ARGS:-}

CC=${CC:-}
CFLAGS=${CFLAGS:-}
CLANG_FORMAT_CHECK=${CLANG_FORMAT_CHECK:-}
CLANG_FORMAT_VERSION=${CLANG_FORMAT_VERSION:-}
CLANG_TIDY=${CLANG_TIDY:-}
CLANG_TIDY_ARGS=${CLANG_TIDY_ARGS:-}
CLANG_TIDY_JOBS=${CLANG_TIDY_JOBS:-}
CMAKE_ARGS=${CMAKE_ARGS:-}
CPPFLAGS=${CPPFLAGS:-}
CXX=${CXX:-}
CXXFLAGS=${CXXFLAGS:-}
CCACHE_DIR=${CCACHE_DIR:-$HOME/.ccache}

DEBUG_BASH=${DEBUG_BASH:-}

DOWNSTREAM_CMAKE_ARGS=${DOWNSTREAM_CMAKE_ARGS:-}
DOWNSTREAM_WORKSPACE=${DOWNSTREAM_WORKSPACE:-}
HASHKEY_SKS=${HASHKEY_SKS:-}
IMMEDIATE_TEST_OUTPUT=${IMMEDIATE_TEST_OUTPUT:-}
LC_ALL=C.UTF-8

NOT_TEST_BUILD=${NOT_TEST_BUILD:-}
NOT_TEST_DOWNSTREAM=${NOT_TEST_DOWNSTREAM:-}
NOT_TEST_INSTALL=${NOT_TEST_INSTALL:-}

OS_NAME=${OS_NAME:-}
OS_CODE_NAME=${OS_CODE_NAME:-}
UBUNTU_OS_CODE_NAME=${UBUNTU_OS_CODE_NAME:-}

PRERELEASE=${PRERELEASE:-}
PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-}
ROSDEP_SKIP_KEYS=${ROSDEP_SKIP_KEYS:-}
ROSINSTALL_FILENAME=${ROSINSTALL_FILENAME:-}

ROS_DISTRO=${ROS_DISTRO:-}
ROS_REPO=${ROS_REPO:-}
ROS_REPOSITORY_PATH=${ROS_REPOSITORY_PATH:-}
DOCKER_IMAGE=${DOCKER_IMAGE:-}
DOCKER_BASE_IMAGE=${DOCKER_BASE_IMAGE:-}
USE_DEB=${USE_DEB:-}

DOCKER_FILE=${DOCKER_FILE:-}
INJECT_QEMU=${INJECT_QEMU:-}
APTKEY_STORE_HTTPS=${APTKEY_STORE_HTTPS:-}
DOCKER_PULL=${DOCKER_PULL:-}
DOCKER_COMMIT=${DOCKER_COMMIT:-}

SSH_AUTH_SOCK=${SSH_AUTH_SOCK:-}

ROS_PYTHON_VERSION=${ROS_PYTHON_VERSION:-}
TARGET_CMAKE_ARGS=${TARGET_CMAKE_ARGS:-}
TARGET_REPO_NAME=${TARGET_REPO_NAME:-}
TARGET_REPO_PATH=${TARGET_REPO_PATH:-}
TARGET_WORKSPACE=${TARGET_WORKSPACE:-}
TERM=${TERM:-}
USE_MOCKUP=${USE_MOCKUP:-}
UPSTREAM_CMAKE_ARGS=${UPSTREAM_CMAKE_ARGS:-}
UPSTREAM_WORKSPACE=${UPSTREAM_WORKSPACE:-}
VERBOSE_OUTPUT=${VERBOSE_OUTPUT:-}
VERBOSE_TESTS=${VERBOSE_TESTS:-}
