name: 'ROS industrial_ci'
description: "Running various CI checks for ROS package repositories"

inputs:
  config:
    description: 'Configuration in JSON format, e.g. from matrix'
    required: false

outputs: # propagate outputs
  pull_docker_image:
    description: "Exit code of step pull_docker_image"
    value: ${{ steps.ici.outputs.pull_docker_image }}
  init:
    description: "Exit code of step init"
    value: ${{ steps.ici.outputs.init }}
  catkin_tools_setup:
    description: "Exit code of step catkin_tools_setup"
    value: ${{ steps.ici.outputs.catkin_tools_setup }}
  setup_rosdep:
    description: "Exit code of step setup_rosdep"
    value: ${{ steps.ici.outputs.setup_rosdep }}
  setup_upstream_workspace:
    description: "Exit code of step setup_upstream_workspace"
    value: ${{ steps.ici.outputs.setup_upstream_workspace }}
  install_upstream_dependencies:
    description: "Exit code of step install_upstream_dependencies"
    value: ${{ steps.ici.outputs.install_upstream_dependencies }}
  build_upstream_workspace:
    description: "Exit code of step build_upstream_workspace"
    value: ${{ steps.ici.outputs.build_upstream_workspace }}
  setup_target_workspace:
    description: "Exit code of step setup_target_workspace"
    value: ${{ steps.ici.outputs.setup_target_workspace }}
  install_target_dependencies:
    description: "Exit code of step install_target_dependencies"
    value: ${{ steps.ici.outputs.install_target_dependencies }}
  build_target_workspace:
    description: "Exit code of step build_target_workspace"
    value: ${{ steps.ici.outputs.build_target_workspace }}
  run_target_test:
    description: "Exit code of step run_target_test"
    value: ${{ steps.ici.outputs.run_target_test }}
  target_test_results:
    description: "Exit code of step target_test_results"
    value: ${{ steps.ici.outputs.target_test_results }}
  install_catkin_lint:
    description: "Exit code of step install_catkin_lint"
    value: ${{ steps.ici.outputs.install_catkin_lint }}
  catkin_lint:
    description: "Exit code of step catkin_lint"
    value: ${{ steps.ici.outputs.catkin_lint }}
  clang_tidy_checks:
    description: "Exit code of step clang_tidy_checks"
    value: ${{ steps.ici.outputs.clang_tidy_checks }}
  setup_downstream_workspace:
    description: "Exit code of step setup_downstream_workspace"
    value: ${{ steps.ici.outputs.setup_downstream_workspace }}
  install_downstream_dependencies:
    description: "Exit code of step install_downstream_dependencies"
    value: ${{ steps.ici.outputs.install_downstream_dependencies }}
  build_downstream_workspace:
    description: "Exit code of step build_downstream_workspace"
    value: ${{ steps.ici.outputs.build_downstream_workspace }}
  run_downstream_test:
    description: "Exit code of step run_downstream_test"
    value: ${{ steps.ici.outputs.run_downstream_test }}
  downstream_test_results:
    description: "Exit code of step downstream_test_results"
    value: ${{ steps.ici.outputs.downstream_test_results }}

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/.github/action.sh
      shell: bash
      id: ici
      env:
        INPUT_CONFIG: ${{ inputs.config }}
