name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: './'
        id: ici
      - name: Check output
        run: |
          echo "${{ join(steps.ici.outputs.test_list, '-')}}"
