name: CI

on:
  push:

jobs:
  moveit2:
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: 'ros-planning/moveit2'
            ref: '2.2.0'
            env: {ROS_DISTRO: galactic, PRERELEASE: true}

          - repo: 'ros-planning/moveit2'
            ref: '2.2.0'
            env: {ROS_DISTRO: galactic, TEST: debians}

          - repo: 'ros-planning/moveit2'
            ref: 'main'
            env: {ROS_DISTRO: galactic, TEST: debians}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout external repository
        uses: actions/checkout@v2
        with:
          repository: ${{matrix.repo}}
          ref: ${{matrix.ref}}
          fetch-depth: ${{matrix.depth}}

      - uses: actions/checkout@v2
        with:
          path: .industrial_ci

      - uses: './.industrial_ci/'
        env: ${{matrix.env}}

